/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardInterviewRouteImport } from './routes/dashboard.interview'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardCoverLetterRouteImport } from './routes/dashboard.cover-letter'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewRoute = DashboardInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoverLetterRoute = DashboardCoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard/cover-letter'
    | '/dashboard/history'
    | '/dashboard/interview'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard/cover-letter'
    | '/dashboard/history'
    | '/dashboard/interview'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard/cover-letter'
    | '/dashboard/history'
    | '/dashboard/interview'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interview': {
      id: '/dashboard/interview'
      path: '/interview'
      fullPath: '/dashboard/interview'
      preLoaderRoute: typeof DashboardInterviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cover-letter': {
      id: '/dashboard/cover-letter'
      path: '/cover-letter'
      fullPath: '/dashboard/cover-letter'
      preLoaderRoute: typeof DashboardCoverLetterRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCoverLetterRoute: typeof DashboardCoverLetterRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardInterviewRoute: typeof DashboardInterviewRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoverLetterRoute: DashboardCoverLetterRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardInterviewRoute: DashboardInterviewRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
